### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jrischma** [OpenCommunityCoin/open-ethereum-pool#3]
Hi, this work with Ethereum Classic ?

**Comment by hackmod** [comment]
there is an ETC variant pool exists.
https://github.com/mikeyb/open-ethereumclassic-pool (recently added by mikeyb)

**Comment by hackmod** [comment]
I guess this is the original https://github.com/LeChuckDE/open-ethereumclassic-pool

**Comment by hackmod** [comment]
I think this is the original pplns+etc+repo https://github.com/boehla/open-ethereum-pool
it looks like it already supports ETC but I'm not sure.
