### ISSUE TITLE
Inverted Order

### ISSUE THREAD

**Issue by jrischma** [OpenCommunityCoin/open-ethereum-pool#5]
hello, the list order is in increasing order, and it should be the reverse order to show the last payments first

![image](https://user-images.githubusercontent.com/11020812/41500704-f61f63d0-7164-11e8-908b-956481ae9ef9.png)

![image](https://user-images.githubusercontent.com/11020812/41500714-3514d84a-7165-11e8-9b43-dd6888c78140.png)

Is it possible to fix this?

thanks!

**Comment by mikule1** [comment]
I need this fix too. 👍

**Comment by hackmod** [comment]
thank you for your reporting! already fixed in my private repo. will update soon!!

**Comment by hackmod** [comment]
fixed at `solo-pool` branch
